/*
 / _____)             _              | |
( (____  _____ ____ _| |_ _____  ____| |__
 \____ \| ___ |    (_   _) ___ |/ ___)  _ \
 _____) ) ____| | | || |_| ____( (___| | | |
(______/|_____)_|_|_| \__)_____)\____)_| |_|
    (C)2015 Semtech

Description: End device commissioning parameters

License: Revised BSD License, see LICENSE.TXT file include in the project

Maintainer: Miguel Luis and Gregory Cristian
*/
#ifndef __LORA_NETARG_H__
#define __LORA_NETARG_H__

/*!
 * Indicates if the end-device is to be connected to a private or public network
 */
#define LORAWAN_PUBLIC_NETWORK                      true

/*!
 * When set to 1 the application uses the Over-the-Air activation procedure
 * When set to 0 the application uses the Personalization activation procedure
 */
#define OVER_THE_AIR_ACTIVATION                     true


#define LORAWAN_ADR_ON                              true

#define LORAWAN_DEVICE_CLASS                        CLASS_A

/*!
 * IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * \remark This is unique to a company or organization
 */
#define IEEE_OUI                                    0x68, 0xda

/*!
 * Mote device IEEE EUI (big endian)
 *
 * \remark In this application the value is automatically generated by calling
 *         BoardGetUniqueId function
 */
#define LORAWAN_DEVICE_EUI                           {IEEE_OUI, 0x00, 0x11, 0x00, 0x00, 0x00, 0x02 }// 68da001100000001

/*!
 * Application IEEE EUI (big endian)
 */
//测试
//#define LORAWAN_APPLICATION_EUI                     { 0x68, 0xd9, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01	 }
//空气小六
//#define LORAWAN_APPLICATION_EUI                       { 0x68, 0xd9, 0x00, 0x00, 0x00, 0x00, 0x00, 0x11}
//土壤
//68da000000000011
#define LORAWAN_APPLICATION_EUI                     { 0x68, 0xda, 0x00, 0x00, 0x00, 0x00, 0x00, 0x11	 }
/*!
 * AES encryption/decryption cipher application key
 */                 
//测试
//#define LORAWAN_APPLICATION_KEY                     { 0xf5, 0x61, 0x17, 0x37, 0x60, 0x53, 0x54, 0x2e, 0x89, 0x44, 0x80, 0xdd, 0x44, 0x6d, 0x9c, 0xb2 }
//空气小六
//#define LORAWAN_APPLICATION_KEY                      { 0x7c, 0x66, 0xd7, 0xff, 0x2c, 0xa6, 0x64, 0xbe, 0x51, 0x28, 0x5d, 0xda, 0x4a, 0x61, 0xb0, 0x5b  }
//土壤 7c66d7ff2ca664be51288dda4a61b05b
#define LORAWAN_APPLICATION_KEY                      { 0x7c, 0x66, 0xd7, 0xff, 0x2c, 0xa6, 0x64, 0xbe, 0x51, 0x28, 0x8d, 0xda, 0x4a, 0x61, 0xb0, 0x5b  }
/*!
 * Current network ID
 */
#define LORAWAN_NETWORK_ID                          ( uint32_t )0

/*!
 * Device address on the network (big endian)
 *
 * \remark In this application the value is automatically generated using
 *         a pseudo random generator seeded with a value derived from
 *         BoardUniqueId value if LORAWAN_DEVICE_ADDRESS is set to 0
 */
#define LORAWAN_DEVICE_ADDRESS                      ( uint32_t )0x00000000

/*!
 * AES encryption/decryption cipher network session key
 */
#define LORAWAN_NWKSKEY                             { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

/*!
 * AES encryption/decryption cipher application session key
 */
#define LORAWAN_APPSKEY                             { 0x2B, 0x7E, 0x15, 0x16, 0x28, 0xAE, 0xD2, 0xA6, 0xAB, 0xF7, 0x15, 0x88, 0x09, 0xCF, 0x4F, 0x3C }

#endif // __LORA_NETARG_H__
